### PR TITLE
Added BrowserNavigationMode

### PR DESCRIPTION
**Pull request by johnpreed**
Now supports both pushState and replaceState when performing an action
on the grid by defining the BrowserNavigationMode. Defaults to
pushState, which was the original implementation. if you only want to
preserve latest action on your grid, then set
.WithBrowserNavigationMode(BrowserNavigationMode.PreserveLatestGridAction)

### CODE REVIEW

**Comment by joeharrison714** [comment]
Not sure why but I am just seeing this. I am checking it out now!

**Comment by joeharrison714** [comment]
Hey John, did you mean to include all the commits that are in this pull request? I would like to pull in the WithBrowserNavigationMode change but I saw some other things like vertical table and some bug fixes. Wasn't sure if that was intentional. I'd like to pull them in too if they apply to everyone.
Thanks,
Joe

**Comment by johnpreed** [comment]
Yeah you can totally pull everything.  I've been using my latest commit for quite a while now with no problems

**Comment by joeharrison714** [comment]
Cool... there are conflicts that need to be resolved. Any chance you could
do that so I can just accept the pull request?

**Comment by johnpreed** [comment]
sure thing! i'll take a look and let you know when it's ready

Date: Wed, 27 Jan 2016 09:45:23 -0800

**Comment by johnpreed** [comment]
Hey Joe,
I think it should be all set.. i'm still getting used to github desktop -- pretty sure i did it right.  have a look and let me know if i screwed it up :)

From: johnpreed@hotmail.com
To: reply@reply.github.com; mvcgrid.net@noreply.github.com
Subject: RE: [MVCGrid.Net] Added BrowserNavigationMode (#24)
Date: Wed, 27 Jan 2016 14:06:13 -0800




sure thing! i'll take a look and let you know when it's ready

Date: Wed, 27 Jan 2016 09:45:23 -0800

**Pull request closed without merging**
